// Fetch a real photo for every watch in data.js and write images.js + img/ (both gitignored:
// brand photos are copyrighted, so they stay on this machine).
//
//   node tools/fetch-images.mjs          only watches without a photo yet
//   node tools/fetch-images.mjs --force  redo everything
import fs from "fs";
import vm from "vm";
import path from "path";
import { fileURLToPath } from "url";
import { fromUrl, fromReference, byName, saveImage } from "./lookup.mjs";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const ctx = { window: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(root, "data.js"), "utf8"), ctx);
const D = ctx.window.HOROLOGY;

const outFile = path.join(root, "images.js");
const prev = fs.existsSync(outFile) ? JSON.parse(fs.readFileSync(outFile, "utf8").replace(/^[^{]*/, "").replace(/;\s*$/, "")) : {};
const force = process.argv.includes("--force");
const imgDir = path.join(root, "img");

async function one(w) {
  if (!force && prev[w.id]?.src) return prev[w.id];
  if (w.level === "brand") return { missing: "brand only, no model chosen yet" };
  if (/category page/i.test(w.variant || "")) return { missing: "saved link is a category page" };

  const reasons = [];
  for (const url of w.urls) {
    const r = await fromUrl(url);
    if (r.ok) {
      for (const im of r.images) {
        try { return { src: "img/" + (await saveImage(im.src, imgDir)), source: r.source, method: im.how, page: url }; } catch {}
      }
      reasons.push(`${r.host}: photo download failed`);
    } else reasons.push(`${r.host}: ${r.reason}`);
  }
  if (w.ref) {
    const hits = await fromReference(w.ref);
    if (hits.length === 1) {
      const h = hits[0];
      try { return { src: "img/" + (await saveImage(h.image, imgDir)), source: h.source, method: h.method, page: h.url, matched: h.title }; } catch {}
    }
    if (hits.length > 1) {
      const choices = [];
      for (const h of hits) { try { choices.push({ src: "img/" + (await saveImage(h.image, imgDir)), source: h.source, title: h.title, page: h.url }); } catch {} }
      if (choices.length) return { choices, missing: "several matches, pick one" };
    }
    reasons.push(`no exact match for ${w.ref}`);
  }
  // Last resort, only for watches with no reference (a name search can't confirm a reference):
  // search by name on the maker's own store and Teddy Baldassarre, offered as choices only.
  const query = [w.maker === "Swatch" ? "" : w.maker, w.model].filter(Boolean).join(" ");
  if (w.model && !w.ref) {
    const stores = [...new Set([...w.urls.map((u) => new URL(u).hostname), "teddybaldassarre.com"])];
    const hits = await byName(query, w.collab && w.maker === "Swatch" ? "swatch" : w.maker, stores);
    const choices = [];
    for (const h of hits) { try { choices.push({ src: "img/" + (await saveImage(h.image, imgDir)), source: h.source, title: h.title, page: h.url }); } catch {} }
    if (choices.length) return { choices, missing: `not sure which: ${reasons.join(" · ")}` };
  }
  if (!w.urls.length && !w.ref) reasons.push("no link or reference");
  return { missing: reasons.join(" · ") || "nothing found" };
}

const all = [...D.owned, ...D.wants];
const result = {};
const queue = [...all];
let done = 0;
await Promise.all(Array.from({ length: 6 }, async () => {
  while (queue.length) {
    const w = queue.shift();
    result[w.id] = await one(w);
    done++;
    const r = result[w.id];
    console.log(`${String(done).padStart(3)}/${all.length} ${r.src ? "✓" : r.choices ? "?" : "✗"} ${w.id.padEnd(28)} ${r.src ? `${r.source} (${r.method})` : r.missing}`);
  }
}));

const ordered = Object.fromEntries(all.map((w) => [w.id, result[w.id]]));
fs.writeFileSync(outFile, `// Generated by tools/fetch-images.mjs. Gitignored: brand photos are copyrighted.\nwindow.HOROLOGY_IMAGES = ${JSON.stringify(ordered, null, 1)};\n`);
const n = Object.values(ordered);
console.log(`\nphotos: ${n.filter((r) => r.src).length} · to pick: ${n.filter((r) => r.choices).length} · missing: ${n.filter((r) => !r.src && !r.choices).length}`);

// Remove downloads nothing points at any more (earlier runs, replaced choices).
// Photos picked or added in the app are listed in img/keep.txt by the local server.
const keepFile = path.join(imgDir, "keep.txt");
const used = new Set(
  [...Object.values(ordered).flatMap((r) => [r.src, ...(r.choices || []).map((c) => c.src)]),
   ...(fs.existsSync(keepFile) ? fs.readFileSync(keepFile, "utf8").split("\n") : [])]
    .filter(Boolean).map((s) => path.basename(s)),
);
let removed = 0;
for (const f of fs.readdirSync(imgDir)) if (f !== "keep.txt" && !used.has(f)) { fs.unlinkSync(path.join(imgDir, f)); removed++; }
if (removed) console.log(`removed ${removed} unused files`);
